export const PROJECTS = [
  {
    id: 0,
    img: "https://placehold.co/600x400",
    lang: ["js", "bootstrap"],
    name: "JSON Formatter",
    description: 'Turns text from name:value into {"name":"value"}.',
  },
  {
    id: 1,
    img: "https://placehold.co/600x400",
    lang: ["js", "tailwind", "react"],
    name: "Portfolio Site",
    description: "This site.",
  },
  {
    id: 2,
    img: "https://placehold.co/600x400",
    lang: ["bootstrap", "python", "tailwind", "react"],
    name: "Project 2",
    description: "test project",
  },
  {
    id: 3,
    // img: "https://placehold.co/600x400",
    lang: ["js", "python", "react"],
    img: "https://placehold.co/600x400",
    name: "Project 3 ",
    description: "test project.",
  },
  {
    id: 4,
    // img: "https://placehold.co/600x400",
    lang: ["js", "python", "react"],
    img: "https://placehold.co/600x400",
    name: "Project 4 ",
    description: "test project.",
  },
  {
    id: 5,
    // img: "https://placehold.co/600x400",
    lang: ["", "python", "react", "bootstrap", ""],
    img: "https://placehold.co/600x400",
    name: "Project 5 ",
    description: "test project.",
  },
];
